redis-session/src/main.rs, template_askama/src/main.rs
When we listen on all network interfaces instead of localhost, Mac shows this pop window. Maybe listening on 0.0.0.0 was not intended?
=> Listen to localhost instead of all network interfaces

template_askama/Cargo.toml
It seems to me that the build dependency section is not required, since it is covered under dependencies. Or am I missing something?
=> Removed duplicate dependency in askama Cargo.toml

.travis.yml, Cargo.lock, Cargo.toml, middleware/Cargo.toml, middleware/README.md, middleware/src/main.rs, middleware/src/redirect.rs, middleware/src/simple.rs
I attempted to make them as minimal as possible, so I did not want to include other already implemented middlewares, for instance for checking the `req.identity()`.
I find that when I'm trying to learn a concept, I want as few distractions as possible.
=> Middleware example

json/src/main.rs
When I raised #39 the Travis build was failing. This is a fix that makes it pass.
There were a couple of ways to fix this, I went for the "destructured arguments" approach. Another would have been something like:
```rust
(cfg.0).0.limit(4096); // <- limit size of the payload
```
I felt the destructuring communicated more about what the closure argument looks like. Let me know if there's a better approach.
=> Fix json example Travis build failure

.travis.yml, Cargo.toml, actix_todo/.env, actix_todo/Cargo.toml, actix_todo/README.md, actix_todo/diesel.toml, actix_todo/migrations/00000000000000_diesel_initial_setup/down.sql, actix_todo/migrations/00000000000000_diesel_initial_setup/up.sql, actix_todo/migrations/2018-07-05-163612_create_tasks_table/down.sql, actix_todo/migrations/2018-07-05-163612_create_tasks_table/up.sql, actix_todo/src/api.rs, actix_todo/src/db.rs, actix_todo/src/main.rs, actix_todo/src/model.rs, actix_todo/src/schema.rs, actix_todo/src/session.rs, actix_todo/static/css/normalize.css, actix_todo/static/css/skeleton.css, actix_todo/static/css/style.css, actix_todo/static/errors/400.html, actix_todo/static/errors/404.html, actix_todo/static/errors/500.html, actix_todo/templates/index.html.tera
This is a port of the [Rocket Todo example](https://github.com/SergioBenitez/Rocket/tree/master/examples/todo) into [actix-web](https://actix.rs/). Except this uses PostgreSQL instead of SQLite.
Is this something you would like to include in these examples?
It integrates:
* Diesel with PostgreSQL
* Tera templates
* Logging
* Serving CSS static files
* Cookie sessions
* Differentiating between PUT and DELETE using a hidden `_method` form field
* Flash messages via the session cookie
Note:
* This is the first code I've written using actix, so it might not be particularly "idiomatic". Please let me know if there are better ways to do things 🙂
* I deliberately used PostgreSQL instead of SQLite because I wanted to create an example using an RDBMS I'm more likely to use in production. Would we …
=> actix-todo example

websocket-chat/src/main.rs, websocket-tcp-chat/src/main.rs, websocket/src/main.rs
The server would ping the client on a regular interval but never actually handled the pong, so the client disconnected after 10 seconds regardless.
=> Fix pinging so client doesn't get dropped automatically after 10 seconds

rustls/Cargo.toml, rustls/src/main.rs
actix-web updated to rustls 0.14. Update the example, as well, to avoid conflicting versions.
(to test this, one needs current master of actix-web, as well, to include commit 32145cf6 "fix after update tokio-rustls")
=> fix rustls example with updated rustls in actix-web

tls/Cargo.toml
In actix-web's Cargo.toml, feature "alpn" is marked as deprecated,
with the suggestion to use "ssl", instead.
=> replace deprecated feature "alpn" with "ssl"

websocket-chat/src/server.rs, websocket-tcp-chat/src/server.rs
interior mutability isn't needed within these actors as the handle
method takes &mut self
also fix compat. w/ rand 0.6
=> remove unneeded RefCells

async_ex1/src/main.rs
Adding the validate macros to the content you want to validate doesn't do anything until you call `.validate()` on the concerning content.
This pull request should fix that issue.
=> fix validation in async_ex1 example

.travis.yml, Cargo.toml, template_yarte/Cargo.toml, template_yarte/README.md, template_yarte/build.rs, template_yarte/src/lib.rs, template_yarte/src/main.rs, template_yarte/templates/deep/more/deep/welcome.hbs, template_yarte/templates/index.hbs, template_yarte/yarte.toml
I would like to emphasize the two functionalities:
- Partials if you throw cargo run you will see the result by stdout.
- Hierarchical name resolution which allows to resolve and create names in different scopes with the minimum code. Resolve within any context, including tuples with _n for the n-th element.
The result is modular templates by composition without cost.
This time for actix_web `1.0`
=> Add template yarte

template_askama/Cargo.toml, template_askama/src/main.rs
This simplifies the code enormously as explicit `render` calls
are no longer needed with askama's actix-web integration.
Discovery on how to enable crate features can be a bit tricky for new users so this could be a helpful resource for new askama users.
=> Update example to most recent askama release

template_askama/src/main.rs
Switches the position of a rogue parenthesis so that the index function is actually called.
=> Fixes parentheses in template_askama main.rs

async_db/src/db.rs, async_db/src/main.rs
Clarified the use of `sleep(Duration::from_secs(2));` by extending the comments at the top of the main.rs and commenting each use with `//see comments at top of main.rs`
=> clarify use of sleep in async_db

Cargo.toml, jsonrpc/Cargo.toml, jsonrpc/README.md, jsonrpc/src/convention.rs, jsonrpc/src/main.rs, jsonrpc/tests/test_client.py
- Passed `cargo fmt` and `cargo clippy`
- Be compared with `hello-world` server, only lose 8% TPS due to json parsing
Ref: #111
=> Add jsonrpc example

http-full-proxy/src/main.rs
This change should fix empty (error) response of http-full-proxy example.
Tested on sample example `./http-full-proxy 127.0.0.1 8080 127.0.0.1 80` and it worked as expected, content from 80 is shown.
=> fix streaming issue in http-full-proxy example

http-full-proxy/src/main.rs
Reverts actix/examples#120
Please revert this change, I was wrong. It works, but I've tried it in combination with [Miniserve](https://github.com/svenstaro/miniserve) and there is `content-encoding: br` header (`br` means Brotli).
There is still issue in case `content-encoding` is `br`, but in other cases proxy works just fine.
(btw. my change was totally wrong, sorry)
=> Revert "fix streaming issue in http-full-proxy example"

async_db/db/setup_db.sh
Fix error that occurs if script is used like in the async_db readme.
Error before this change:
``` bash
$ LANG=C bash db/setup_db.sh
db/setup_db.sh: line 2: db.sql: No such file or directory
Error: cannot open "nyc_centralpark_weather.csv
```
=> Fix bug in database script

state/src/main.rs
Fix bug in state type 
```rust
let counter = Arc::new(Mutex::new(0));
```
may not be usize
Error before this change:
```
App data is not configured, to configure use App::data()
```
=> Fix bug in state type

async_ex1/src/main.rs
Pretty much a mirror of #83, the validation was lost in the examples migration from 0.7 -> 1.0.
=> add unused validation to async_ex1 example

middleware/README.md, middleware/src/simple.rs
I'm looking at how to do middleware in 1.0 and noticed a couple of typos. GIt log suggests you accept trivial fixes like this, so I fixed them, even though they're inconsequential.
=> Fixes trivial typos.

diesel/.env, diesel/README.md, diesel/src/main.rs
`diesel migration run` created a file named `file:test.db` and the application an empty `test.db`.
=> Read SQLite path from .env and fix DATABASE_URL

template_handlebars/src/main.rs
It isn't necessary to encapsulate the `Handlebars` struct inside an atomic reference-counting pointer, as `actix_web::web::Data` already uses an `Arc` internally (as specified in https://docs.rs/actix-web/1.0.2/actix_web/web/struct.Data.html).
Thanks ! :)
=> Avoid double Arc inside template_handlebars

Cargo.toml, json_error/Cargo.toml, json_error/src/main.rs
Based on our discussion in https://github.com/actix/actix-web/issues/924.
Figured it could help others with error messages, as error_response worked in 0.7 the way that render_response does in 1.0.
=> Added json_error example.

http-full-proxy/src/main.rs
If you decompress a proxied response that was encoded, the `content-encoding` header will be passed through but a plaintext body will be returned.
=> Do not decompress proxied responses

websocket/Cargo.toml, websocket/src/client.rs
In this PR, a working example for websocket client is given.
The new API split Framed object into sink and stream to obtain writer and reader. And I found a helper struct `SinkWrite` in `actix::io`, which can hold sink object and provide an easy way to send message through Sink, as `Sink::send(self, item:Self::Item)` consumes Sink object.
Related to #123 and this issue in [actix-web](https://github.com/actix/actix-web/issues/829).
After a few days of trial and error, I have figure out a way to write websocket client with actix-web 1.0, or rather, awc and actix-codec. So maybe it's better to create a new example folder, as the dependencies in server and client are quite different.
Minimal dependencies for server:
```toml
[dependencies]
actix = "0.8.2"
actix-web = "1.0.0"
actix-web-actors = …
```
=> Update websocket client example to actix-web 1.0

.gitignore
Ignore `upload.png` generated in multipart example
=> Ignore multipart example's png

basics/static/404.html, basics/static/welcome.html
Replaces `href="/favicon.ico"` with `href="/favicon"` (and formats styles)
=> Fix favicon link on basics

Cargo.toml, server-sent-events/Cargo.toml, server-sent-events/README.md, server-sent-events/benchmark.js, server-sent-events/drain.js, server-sent-events/src/index.html, server-sent-events/src/main.rs
Issue #32, without `HttpContext` though.
~~Lacks mechanism to remove clients / connections when not receiving broadcast messages, which may starve file descriptors and hinder new HTTP connections.~~
Edit: Updated to clean stale clients every 10 seconds.
=> server-sent events

.travis.yml, template_yarte/src/main.rs
When I run the tests for the `template_yarte` example I am getting the following failure:
```
---- test::test stdout ----
thread 'test::test' panicked at 'assertion failed: `(left == right)`
left: `"text/html; charset=utf-8"`,
right: `"text/html"`', template_yarte/src/main.rs:45:9
```
This probably went undetected since our CI pipeline doesn't run the unit tests, it only run `cargo check`.
=> Several tests are failing

form/Cargo.toml, form/src/main.rs
It would be helpful to have tests for the various examples (ref. #73).
This PR adds unit tests and integration tests for all the POST request handlers in the form example.
I have factored out the app configuration to a separate function so it can be reused in the integration tests. The version bump is needed because the integration tests are using `test::TestRequest::set_form()` method which was added recently in https://github.com/actix/actix-web/pull/1058
This is my first contribution to actix-web so if there are certain things that can be done in an easier or better way I would be happy to improve the PR.
=> Provide tests for the form example

http-proxy/src/main.rs
Without doing this, body size would be unknown at the time of sending, causing awc to use transfer encoding which is probably unexpected in most cases.
This change makes behavior more obvious.
=> Always send body whole and don't use transfer encoding

form/src/main.rs, template_handlebars/src/README.md
The current form example can't be tested since `get_app_data()` has been removed.
Also fixes a typo on README of template_handlebars.
=> Fix form example's test

basics/src/main.rs
Basics example had a semicolon instead of a comma, causing logging not to work properly.
=> Fix logging in basics example

basics/README.md
A wrong route is given in the readme file. The correct route is /async-body/{name}.
=> Fix path name on /examples/basics

basics/README.md
In my last merge request, I missed to adjust the text, so the link does not match the displayed text.
=> Fix path-text on /examples/basics 

Cargo.toml, multipart-async-std/.gitignore, multipart-async-std/Cargo.toml, multipart-async-std/LICENSE, multipart-async-std/README.md, multipart-async-std/src/main.rs
In this PR I use `async_std` instead of blocking. Moreover, I treat all errors. I hope this makes the code more streamlined.
=> Use async-std in multipart example and treat all errors

websocket-tcp-chat/src/main.rs
Fixes #115
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
=> Arbiter::exec to start TcpServer will not work, simply call it

README.md
Casbin example is merged in: https://github.com/actix/examples/pull/264
=> Add Casbin example to README

Cargo.toml, json_decode_error/Cargo.toml, json_decode_error/README.md, json_decode_error/src/main.rs
A demonstration of how you can return something more informative to the client than an empty HTTP 400 in cases where deserializing a JSON payload fails.
Please let me know if the coding style, documentation, naming or anything else can be improved, I am not very experienced with programming in Rust yet!
=> New example: Return JSON decode errors to a client

multipart-async-std/src/main.rs, multipart/src/main.rs
**Error scenario:**
A wrong programmed client or a html form without enctype sends the data as application/x-www-form-urlencoded (even if there is a file input in the form or the method is set to "post"). Such requests will be handled by the multipart handler. The example panics if it receives such a request.
**Fix:**
Use a TryStreamExt ( try_next() ) instead of a StreamExt ( next() ) to iterate over the fields, so a malformed request don't cause a panic.
**Test data:**
Use the following package to test the scenarios: [actix_playground.zip](https://github.com/actix/examples/files/4362777/actix_playground.zip)
Information:
I wrote this test program under and for Linux. I don't know if it works on Windows as well.
Preparations:
1. Build and run the test program (cd into the directory and …
=> Fixed possible panic in multipart example

shutdown-server/src/main.rs
=> Remove unused variable _stopper in shutdown-server example

README.md
MeiliSearch very recently migrated from Tide to actix-web: https://github.com/meilisearch/MeiliSearch/pull/601
=> Add MeiliSearch as production example

juniper/src/schema.rs
Juniper crate can interconvert a GraphQL camel function and a Rust snake function.
So a function name in Rust should be snake case.
Actually, functions are written by snake case in juniper-advenced.
https://github.com/actix/examples/blob/master/juniper-advanced/src/schemas/root.rs#L104
=> Fix function name that camel to snake

Cargo.toml, websocket-autobahn/Cargo.toml, websocket-autobahn/README.md, websocket-autobahn/config/fuzzingclient.json, websocket-autobahn/reports/.gitignore, websocket-autobahn/src/main.rs
**This PR**
Hopefully creates a minimal autobahn websocket server example from which to start testing and addressing issues for https://github.com/actix/actix-web/issues/1006.
I assume this example needs to be tweaked slightly to make a reasonable benchmark. From there I can run the autobahn test suite and document all the failures. Then we can pick them off as we see fit.
=> Add bare-bones WS server for autobahn testing

Cargo.toml, udp-echo/Cargo.toml, udp-echo/src/main.rs
The current `udp-echo` example is based on `actix` `0.7` and `tokio` `0.1` and it is too old to be really useful.
This PR updates the code to be compatible and use the current version of `actix` and `tokio`.
Because of the refactors of the dependencies new dependencies came in:
* `tokio-util`
* `futures-util`
Closes #292
=> Update udp-echo example to actix 0.9 and tokio 0.2.

websocket-autobahn/src/main.rs, websocket-chat-broker/src/session.rs, websocket-chat/src/main.rs, websocket-tcp-chat/src/main.rs, websocket/src/main.rs
Fixes https://github.com/actix/actix-web/issues/1555
=> send the correct exit code when closing the websocket

Cargo.toml, async_data_factory/Cargo.toml, async_data_factory/README.md, async_data_factory/src/main.rs
`App::data_factory` can be used to optimize async tasks between works
closes #256
=> add example for App::data_factory

rustls/README.md
For some reason mkcert default generated sertificate doesn't work. Only after you convert it to rsa problem goes away.
```
let mut tls_config = ServerConfig::new(NoClientAuth::new());
let cert_file = &mut BufReader::new(File::open("./tls/localhost/cert.pem").unwrap());
let key_file = &mut BufReader::new(File::open("./tls/localhost/key.pem").unwrap());
let cert_chain = certs(cert_file).unwrap();
let mut keys = rsa_private_keys(key_file).unwrap();
tls_config
.set_single_cert(cert_chain, keys.remove(0))
.unwrap();
```
Rust panic on `keys.remove(0)`.
=> Example tip for key.pem to work

diesel/src/actions.rs
The previous doc comment was referring to the insert_new_user function
=> Fix find_user_by_uid's doc comment

json_decode_error/src/main.rs
Show how to use a global `JsonConfig` in the json_decode_error example.
=> Improve json_decode_error example.

README.md
:heavy_check_mark: **Changes:**
- **Replaced `Casbin-RS` with `Actix-Casbin`**: `Casbin-RS` is not written using Actix although there is an Actix integration of Casbin at https://github.com/casbin-rs/actix-casbin.
- **Removed `actix-raft`**: `actix-raft` is now [`async-raft`](https://github.com/async-raft/async-raft) and no longer uses Actix, they ported their codebase to use the [Tokio](https://github.com/tokio-rs/tokio) framework.
- **Removed `Broker`**: Broker no longer uses Actix, they ported their codebase to use the [Portal](https://docs.rs/portal/0.2.3/portal/) framework (hard-fork of [warp](https://github.com/seanmonstar/warp)).
:books: **Sources:**
- https://github.com/casbin/casbin-rs/issues/82
- https://github.com/apibillme/broker/issues/6
- …
=> Update the examples list

juniper/Cargo.toml, juniper/src/main.rs
Added actix_cors to get Juniper example to work. The example wouldn't work without it for me. I'm on macOS Catalina using Firefox and Safari browsers. The example would fail with a network error.
=> add Cors to get juniper example to work.

web-cors/frontend/package.json
**I tested on my local machine and got a version mismatch, then fixed by changing to the same version.**
`$ npm run serve
> frontend-vue@0.1.0 serve /home/user/rust/examples/web-cors/frontend
> vue-cli-service serve
INFO  Starting development server...
98% after emitting
ERROR  Failed to compile with 2 errors                                   1:58:01 PM
error  in ./src/app.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):
Vue packages version mismatch:
- vue@2.6.10 (/home/user/rust/examples/web-cors/frontend/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.12 (/home/user/rust/examples/web-cors/frontend/node_modules/vue-template-compiler/package.json)
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are …
=> fix version mismatch of "@vue/cli-service"

Cargo.lock, web-cors/backend/Cargo.toml
#371 added actix-cors 0.4 but it didn't update the lockfile. And we use the cors 0.3 in the `web-cors` example so we have two versions of the cors currently, this updates the latter and the lockfile.
=> web-cors: Update `actix-cors` to 0.4

rustls/README.md, rustls/src/main.rs
By default `mkcert` and I think Let's Encrypt will generate `pkcs8` keys. This PR fix default key usage and ads tip for `rsa` keys.
=> Fix rustls example to support pkcs8 keys

Cargo.lock, simple-auth-server/Cargo.toml, simple-auth-server/README.md, simple-auth-server/src/utils.rs
`argonautica` is unmaintained and we currently depend on it by a commit hash. We could replace it with an alternative crate to maintain, I'd introduce `rust-argon2` (https://crates.io/crates/rust-argon2). That crate is well-used and enough to demonstrate, I think. This drops some old crates from our deps 🎉 
cc @mygnu, as this will affect your post.
=> Use `rust-argon2` instead of less-maintained `argonautica`

.github/workflows/clippy-fmt.yml, .github/workflows/linux.yml, Cargo.lock, Cargo.toml, database_interactions/sqlx_todo/.env.example, database_interactions/sqlx_todo/.gitignore, database_interactions/sqlx_todo/Cargo.toml, database_interactions/sqlx_todo/README.md, database_interactions/sqlx_todo/schema.sql, database_interactions/sqlx_todo/src/main.rs, database_interactions/sqlx_todo/src/todo/model.rs, database_interactions/sqlx_todo/src/todo/routes.rs
Switches the example to use sqlite and adds sqlite3 to the CI.
_Closes #412_
=> Fix sqlx_todo CI checks

graphql/juniper/README.md
The link to the `juniper-advanced` example is missing the `graphql` part of the path.
=> Fix a broken link

security/rustls-client-cert/README.md
This PR updates the README in the  rustls-client-cert example to demonstrate [how to pass in the rootCA with httpie](https://httpie.io/docs#custom-ca-bundle).
=> Update rustls-client-cert README to use httpie verify

websockets/websocket/src/main.rs
http://localhost:8080/ws/index.html gives a 404.  The running server serves `index.html` for the page, and connects to the websocket on `/ws`.
See below:
https://github.com/actix/examples/blob/c3407627d0e45ee8883b1c7d1dc84251ecc6d9a1/websockets/websocket/src/main.rs#L108-L110
=> [EZ] Update comment with correct URL.

basics/docker_sample/Dockerfile
The Docker sample project builds the Docker container using the `rust:1-slim-buster` image, that contains the full Rust toolchain to compile the sample application. The final container does not require the toolchain to run the application with, therefore the smaller Debian base image `buster-slim` is sufficient.
This reduces the image size from about ~626 Mb down to ~80 Mb.
=> Use smaller Debian base image in example

README.md
Hi there! I've been using Actix for a while now, and really like it. It offers great performance for my project, [atomic-server](https://github.com/joepio/atomic-data-rust/). Would you like to add it to the showcase list in the examples readme?
=> Add atomic-server to Community Showcase

template_engines/askama/Cargo.toml, template_engines/askama/src/main.rs
Only askama in the template example did not have a Logger.
If you are able to accept the changes here, please consider it.
=> add logger for askama template example

Cargo.lock, security/casbin/Cargo.toml
From v2.0.6 on casbin only supports tokio 1.x which conflicts with actix-web 3,
see see https://github.com/casbin/casbin-rs#installation. This commit pins
the casbin dep at v2.0.5 and makes the casbin example work again with current
stable actix-web, i.e. v3.
Please note that once actix-web v4 is out on crates.io, this commit will probably
need to be reverted.
=> Fix casbin example for actix-web v3

Cargo.lock, security/casbin/Cargo.toml, security/casbin/src/main.rs
...by exchanging the std::sync::RwLock with a
async_std::sync::RwLock. This could also have been the tokio
equivalent but I've used async_std::sync::RwLock as it has nearly the
same API as its std counterpart used in the original casbin example code.
Closes #470
=> Fix deadlock in casbin example

basics/state/Cargo.toml, basics/state/src/main.rs
Issues encountered: deprecated function `App::data` was replaced with
`App::app_data` as suggested in the deprecation notice.
=> Update basics/state to v4.

Cargo.lock, basics/middleware-ext-mut/Cargo.toml, basics/middleware-ext-mut/README.md, basics/middleware-ext-mut/src/add_msg.rs
I switched `println!` to be `log::info` given that the example initialises a logger.
I also simplified the trait bounds on the middleware itself.
=> Update basics/middleware-ext-mut to v4

forms/form/Cargo.toml, forms/form/src/main.rs
Updated to the new `app_data` method in the constructor. Redid the conversion of response body to `str` as the previous one did not work with the new version's interface.
=> Updated forms/form to v4.

basics/shutdown-server/Cargo.toml, basics/shutdown-server/src/main.rs
Moved from `data` to `app_data` in the constructor for `HttpServer`. Rather than cloning the server we now get the handle with `.handle()`.
=> Updated basics/shutdown-server to v4.

Cargo.lock, database_interactions/basic/Cargo.toml, database_interactions/basic/src/db.rs, database_interactions/basic/src/main.rs, database_interactions/r2d2/Cargo.toml, database_interactions/r2d2/src/main.rs, database_interactions/sqlx_todo/Cargo.toml, database_interactions/sqlx_todo/README.md, database_interactions/sqlx_todo/setup_db.sh, database_interactions/sqlx_todo/src/main.rs, database_interactions/sqlx_todo/src/todo/model.rs
They had to be updated together due to the shared dependency on the sys crate for sqlite.
=> Update db/basic, db/sqlx_todo and db/r2d2 to v4

Cargo.lock, basics/middleware/Cargo.toml, basics/middleware/src/main.rs, basics/middleware/src/read_request_body.rs, basics/middleware/src/read_response_body.rs, basics/middleware/src/redirect.rs, basics/middleware/src/simple.rs
I struggled quite a bit with the redirect middleware due to the requirement of unifying the two different body types (a concrete `BoxBody` with a generic `B` body). 
In the end I opted to use an async block because spelling out the type of `MapOk`, required to call `map_into_boxed_body` on the future returned by `service.call`, was getting out of hand.
=> Update basics/middleware to v4

basics/middleware-http-to-https/Cargo.toml, basics/middleware-http-to-https/src/main.rs
I needed to add a new dependency `rustls-pemfile` as the functions for parsing pemfiles are no longer in the core `rustls`.  The `main` function has expanded as the keys and certificates now need to move into `Certificate` and `PrivateKey` structs to be parsed into the `config`.
=> Updated basics/middleware-http-to-https to v4.

security/awc_https/Cargo.toml, security/awc_https/README.md, security/awc_https/src/main.rs
As `actix_web::client` is no more in v4 I added `reqwest` to make Http requests. I removed `openssl` as a dependancy as `reqwest::Client` implements tls by default.
=> Updated security/awc_https to v4.

Cargo.lock, template_engines/handlebars/Cargo.toml, template_engines/handlebars/src/main.rs
The `EitherBody` requirement on error handlers drove me a bit crazy.
=> Update template-engines/handlerbars to v4

server-sent-events/src/broadcast.rs, server-sent-events/src/main.rs
You generally don't want to lock a `Mutex` directly in async code, since that easily results in hard-to-read errors about Send, or worse, deadlocks. This changes an example so that the mutex is instead locked in non-async functions, which can then be called from the async code.
It also removes some unnecessary uses of the stream wrappers in `tokio-stream`.
=> Don't use mutex directly in async code

websockets/chat-tcp/src/client.rs
I found the indentation was broken and fixed it.
=> fix typo for websockets/chat-tcp/client.rs

README.md
This PR adds [rustypaste](https://github.com/orhun/rustypaste) (which uses Actix 4) to community showcase section in README.md
=> Add rustypaste to community showcase

Cargo.lock, databases/postgres/Cargo.toml, databases/postgres/src/main.rs
Fix config code to account for breaking changes when updating.
Note, I updated to most recent .13.1, not .12 as per #537 
I followed this example code for the config changes:
https://github.com/mehcode/config-rs/blob/master/examples/env-list/main.rs
I ran the server and ran the example request, and saw no errors.
=> Fixes #537, Update dependencies for databases/postgres

Cargo.lock
rhei was failing to build due to https://github.com/rhaiscript/rhai/issues/546.  Fixed with `cargo update`.
=> Update Cargo.lock to fix the build

Cargo.lock, auth/simple-auth-server/src/register_handler.rs, databases/diesel/src/main.rs, forms/multipart-s3/src/main.rs, graphql/juniper-advanced/src/main.rs, graphql/juniper-advanced/src/schemas/product.rs, graphql/juniper-advanced/src/schemas/root.rs, graphql/juniper-advanced/src/schemas/user.rs, protobuf/src/main.rs
This PR includes #556
* remove unneeded mut
* use explicit `use` instead of the less precise `extern crate` in a simple case
* minor spacing cleanup
=> Minor lints and clippies

Cargo.lock, auth/cookie-session/Cargo.toml, auth/cookie-session/src/main.rs
- Updated the actix-session dependency to 0.6.
- Changed the CookieSession (which is removed in 0.6) to a CookieSessionStore built with MiddlewareSessionBuilder. 
- The RUST_LOG level was set to  which had the effect of hiding the logs created by the cookie_session (main) application. Changed RUST_LOG to be set to `info` so that all logs are shared.
=> Updated actix-session version to 0.6 in examples/auth/cookie-session

basics/hello-world/src/main.rs
Hello. This is a pretty insignificant change, but I noticed that the hello-world example uses 2 unwraps in the tests even though it returns a `Result`, so I thought that it should use `?` instead of `.unwrap()`. This PR changes 2 lines of code in the `test_index` test.
=> Replace all unwraps in hello-world example with ? operator

auth/simple-auth-server/README.md
There is no registered route to /invitation/{invitation_id}. Instead, it is /register/{invitation_id}
=> update register link to match correct path

auth/cookie-auth/src/main.rs
Running the example as it is currently results in a panic at startup:
```
panicked at 'called `Result::unwrap()` on an `Err` value: TooShort(32)', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.16.1/src/secure/key.rs:63:28
```
This is because the example creates a secret key of 32 bytes, but the required size is `COMBINED_KEY_LENGTH` which is 64 bytes.
Because the docs for `SessionMiddleware` refer to this as a secret key, and because `private key` usually refers to a TLS key in HTTP contexts, I also changed the comment and variable name.
=> Fix bug in cookie-auth example where secret is too short

basics/basics/src/main.rs
The code for service "/async-body/{name}" will not render non ascii input correctly, because the HTTP response header is not set to use charset UTF-8. 
Test on localhost:
Before:
After:
=> add content_type for basic example response body to decode utf-8 correctly

databases/rbatis/README.md
The "rbatis example with actix-web" content in the original documentation is **invalid**
I found a example that shows "how rbatis works with actix" from the documentation of the new version of **rbaits-v4**
https://github.com/rbatis/rbatis/blob/master/Readme.md?plain=1#L30-L31
=> Fix invalid non-existent link (for database example:rbatis).

databases/sea-orm/README.md
In my research, 
I found that SeaORM (https://github.com/SeaQL/sea-orm) supports actix (v4 and v3) 
I thought it might be appropriate for our repo.
=> Add SeaORM in examples/databases.

auth/cookie-auth/src/main.rs
Fixing:
"severity": 8
"message": "cannot move out of `secret_key` a captured variable in an `Fn` closure\nmove occurs because `secret_key` has type `Key`, which does not implement the `Copy` trait",
"severity": 4,
"message": "unused import: `rand::Rng`\n`#[warn(unused_imports)]` on by default"
=> bugs and warning fixes

databases/sqlite/db/README.md
No file named sqlite_db.sh exists in the folder, so I assume the correct one would be setup_db.sh.
=> Fix incorrect spelling of file setup_db.sh

auth/simple-auth-server/src/utils.rs
=> auth/simple-auth-server: fix panic due to default `SECRET_KEY` being 32 bytes, not 64 bytes

https-tls/openssl-auto-le/src/main.rs, https-tls/openssl/src/main.rs, https-tls/rustls-client-cert/src/main.rs, https-tls/rustls/src/main.rs
When exploring the https-tls examples, I noticed that the URIs printed to screen were using the wrong protocol.
This PR corrects the protocol to use https, so that if you click on the link it works as expected.
=> https-tls: typo - correct logged URIs to use https

server-sent-events/README.md
curl likes the request method to be all-caps; the request method isn't accepted otherwise.
=> change `curl -X post` to `curl -X POST`

server-sent-events/drain.js
drain.js was failing to run in node 14, 16, and 18, with the following error:
```
/home/user/actix/examples/server-sent-events/drain.js:32
.post('http://127.0.0.1:8080/', () => print_status(true))
^
TypeError: http.post is not a function
at Timeout._onTimeout (/home/mclayton/projects/mwc/actix/examples/server-sent-events/drain.js:32:6)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
```
I replaced `http.post` with `http.request`.
=> fix server-sent-events/drain.js

databases/postgres/src/main.rs
Added support to postgres docs for querying all users using existing get_users.sql. 
Closes #628
=> feat: update example api to support GET /users

websockets/chat/client.py
Hello,
This pull request addresses an issue with the Python client in the WebSocket chat example. The client prefixes the username and a colon to all messages before sending them to the server. This interferes with server commands like `/join`, `/list`, and `/name`.
Relevant code from the Python client (examples/websockets/chat/client.py):
```python
while line := await asyncio.to_thread(sys.stdin.readline):
await ws.send_str(name + ": " + line)
```
Relevant code from the Rust session (examples/websockets/chat/src/session.rs):
```rust
ws::Message::Text(text) => {
let m = text.trim();
if m.starts_with('/') {
let v: Vec<&str> = m.splitn(2, ' ').collect();
// ...
}
// ...
}
```
The server expects commands to start with a `/`, but because the client prefixes the username to all messages, …
=> Fix Websockets/Chat: Prefixing Username to Messages Interferes with Server Commands

websockets/chat/README.md
I did just test this example. I realized that `pip3 install --requirements requirements.txt` and I suggest to always use a venv when using python to separate dependencies
=> fix python docs and added venv

json/jsonrpc/src/convention.rs
added skip_serialization for JSON fields that should not be present if value is None
=> fix: added skip_serialization for JSON fields

Cargo.lock, Cargo.toml, middleware/middleware-rate-limit/Cargo.toml, middleware/middleware-rate-limit/src/main.rs, middleware/middleware-rate-limit/src/rate_limit.rs
closes #600
This pr contains two implement about rate-limit.
One is [actix-governor](https://github.com/AaronErhardt/actix-governor).
Other is a simple example by implement [token bucket](https://en.wikipedia.org/wiki/Token_bucket).
=> Add rate-limit example

graphql/juniper-advanced/mysql-schema.sql, graphql/juniper-advanced/src/schemas/root.rs
This PR addresses two issues I ran into while running the "juniper-advanced" example:
- Encoding error in mysql-schema.sql
- I'm admittedly not sure how broadly useful this is, as I don't regularly use mysql but I had to replace instances of `utf8mb` with `utf8` and `utf8mb4_0900_ai_ci` with `utf8_general_ci` in order to import the DB schema. I'm running: `mysql  Ver 15.1 Distrib 10.5.21-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper`
- Fix schema descriptions in root.rs which were referring to the wrong table (`user` => `product`)
=> Fix small issues in juniper-advanced example

README.md
rustfulapi has switched to axum https://github.com/robatipoor/rustfulapi/pull/12 meanwhile the jelly repository has been deleted now
=> Remove rustfulapi and jelly starter

unix-socket/src/main.rs
I was momentarily confused about where the example was actually listening.
=> Correct startup log message for unix-server

README.md
Added [trieve](https://github.com/devflowinc/trieve) to Actix examples/community showcase.
=> Added trieve to example showcase

databases/postgres/README.md
Update .env var syntax to use underscores instead of dots, which cause an error difficult to debug if you are not familiar with Confik.
=> fix env vars in postgres readme

websockets/chat-tcp/README.md
Prior to this change if you followed the websockets/chat-tcp README without first making your current directory websockets/chat-tcp, you would get a panic when you opened http://localhost:8080/ .
This uses `include_str!()` to include the index.html file at compile time referencing it relative to the source code file and avoids the use of the problematic `unwrap()` all together.
=> Fix chat-tcp panic when current directory is not the expected directory

.vscode/settings.json, Cargo.lock, justfile, websockets/echo/Cargo.toml, websockets/echo/src/main.rs, websockets/echo/src/server.rs
just demo-ing this actor lib: https://crates.io/crates/ractor
=> Ractor WebSockets

Cargo.lock, Cargo.toml, https-tls/acme-letsencrypt/Cargo.toml, https-tls/acme-letsencrypt/src/main.rs, https-tls/cert-watch/Cargo.toml, https-tls/cert-watch/src/main.rs, https-tls/rustls-client-cert/Cargo.toml, https-tls/rustls-client-cert/src/main.rs, https-tls/rustls/Cargo.toml, https-tls/rustls/src/main.rs, middleware/http-to-https/Cargo.toml, middleware/http-to-https/src/main.rs
Usage of rustls-pemfile isn't necessary, rustls itself provides easier interface to load keys and certificates.
This looks a bit shorter and, hopefully, easier to read.
=> Simplify rustls usage

.github/workflows/ci-nightly.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, databases/diesel-async/Cargo.toml, databases/diesel-async/README.md, databases/diesel-async/diesel.toml, databases/diesel-async/migrations/00000000000000_diesel_initial_setup/down.sql, databases/diesel-async/migrations/00000000000000_diesel_initial_setup/up.sql, databases/diesel-async/migrations/2025-01-18-144029_create_items/down.sql, databases/diesel-async/migrations/2025-01-18-144029_create_items/up.sql, databases/diesel-async/src/actions.rs, databases/diesel-async/src/main.rs, databases/diesel-async/src/models.rs, databases/diesel-async/src/schema.rs
I think it's useful nowadays to have a code example like this as a starting point.
=> Diesel-async usage example

auth/casbin/README.md, guards/README.md
=> Fix typo extra `` 

Cargo.lock, databases/postgres/Cargo.toml, databases/postgres/src/config.rs, databases/postgres/src/main.rs
This PR updates deps, fixes clippy warnings and uses ThinData instead of Data for db pool.
As mentions in [this](https://github.com/actix/examples/discussions/1153#discussioncomment-14287197) discussion, `ThinData` should be used here.
=> Update Postgres example to use ThinData
