- basics/README.md
- basics/src/main.rs
- Change `plain/text` to `text/plain` in [basics/README.md](https://github.com/actix/examples/blob/master/basics/README.md)
- Change `test/plain` to `text/plain` in [basics/src/main.rs](https://github.com/actix/examples/blob/master/basics/src/main.rs)
> typos -> text/plain

- .travis.yml
- Cargo.lock
- Cargo.toml
- form/Cargo.toml
- form/README.md
- form/src/main.rs
- form/static/form.html
Examples on how to handle form submits
Closes #24
> Form example

- multipart/src/main.rs
Add state to the multipart example
> Add state to the multipart example

- basics/src/main.rs
> make the code neater

- state/src/main.rs
As pythoneer argues in https://github.com/actix/actix-web/issues/531,
a realistic counter should count the absolute number of page loads,
and not per-thread counts.
Adding Arc<Mutex<...>> to the state example only increases the
complexity slightly, but is probably more helpful to a reader who just
wants to save some global state.
> Encapsulate app state in Arc<Mutex<...>>

- basics/static/404.html
> fix return home link bug

- Cargo.toml
- template_handlebars/Cargo.toml
- template_handlebars/src/README.md
- template_handlebars/src/main.rs
- template_handlebars/static/templates/index.html
- template_handlebars/static/templates/user.html
> Adds Handlebars example

- http-proxy/Cargo.toml
- http-proxy/src/main.rs
> resolve issue 139

- template_yarte/Cargo.toml
- template_yarte/README.md
- template_yarte/src/main.rs
> Bump yarte version to 0.2.1

- http-full-proxy/src/main.rs
Solves `content-length` issues with postman, #142.
> Full proxy omit content length

- .travis.yml
Fixes some cache errors on Travis
ref. https://levans.fr/rust_travis_cache.html
Other opinions and advice are welcome.
**EDIT**: and it seems clippy is not working so I try to fix
> Prevent jobs from being terminated on Travis

- middleware/src/main.rs
It's a neat little feature and should be shown off.
This also plays into #125.
> Add middleware example with wrap_fn

- cookie-session/Cargo.toml
- cookie-session/README.md
- cookie-session/src/main.rs
> Make cookie-session example clarify

- hello-world/src/main.rs
- json/src/main.rs
Add test
This PR comes from #84 and #85
> Add tests in examples

- Cargo.toml
- template_yarte/Cargo.toml
- template_yarte/src/main.rs
Update to support `actix-web` at version `2.0.0-alpha`
> Update template yarte

- cookie-auth/README.md
It took me some time to figure out how this is meant to work. 
@fafhrd91 Hope you find this doc useful.
> Add some docs and curl example

- template_tera/Cargo.toml
- template_tera/src/main.rs
- todo/Cargo.toml
- todo/src/api.rs
- todo/src/main.rs
> Update `tera` to 1.0

- websocket/README.md
http://localhost:8080/ws/index.html => http://localhost:8080/index.html
> Fixed websocket/README.md: web client url typo

- README.md
A small update to the readme.md file to also showcase the actix-raft project.
> Add the actix-raft project to the community references

- websocket/src/client.rs
The SinkWrite part of websocket client framed required a signature of `SinkWrite<Message, SplitSink<Framed<BoxedSocket, Codec>, Message>>`. However, for histotical reason that in awc 0.2.0, `awc::connect::BoxedSocket` is not exposed to public, users have to use generic type to bypass private struct `BoxedSocket`, and leave the rust compiler to infer data type automatically. 
In websocket client case with awc 1.0, we have to signature `ChatClient` as follow: 
```rust 
struct ChatClient(SinkWrite<Message, SplitSink<Framed<T, Codec>, Message>>)
where T: AsyncWrite + AsyncRead;
```
As Trait implementation on `ChatClient` must follow this generic signature, this led to more complex API and increased compile time.
Luckily, in later version `awc` crate, `BoxedSocket` is exposed to public. 
As in …
> simplify websokcet client example with BoxedSocket

- README.md
I created a real-time zero-code API server using Actix-Web, Sled, and SSE. It is a great example of using Actix-Web as it shows how to build a server with Authentication, State, JWT, passwords, CORS, JSON, SSE, and integration testing. Thanks!
> add broker to readme

- template_yarte/src/main.rs
The behavior has been changed from https://github.com/botika/yarte/commit/c4999d81ed1597663b35ab44735908ee8c8852d7.
> Fix yarte test

- simple-auth-server/Cargo.toml
- simple-auth-server/README.md
- simple-auth-server/src/auth_handler.rs
- simple-auth-server/src/invitation_handler.rs
- simple-auth-server/src/main.rs
- simple-auth-server/src/models.rs
- simple-auth-server/src/register_handler.rs
https://github.com/serde-rs/serde/issues/1441#issuecomment-445481084
> simple-auth-server - use derive feature from serde 

- async_db/Cargo.toml
- async_ex1/src/main.rs
- async_ex2/Cargo.toml
- template_askama/Cargo.toml
- web-cors/backend/Cargo.toml
Unused deps found with https://github.com/est31/cargo-udeps
> Remove validator macro_use. Remove unused deps.

- state/src/main.rs
With reference to https://github.com/actix/actix-web/issues/1272
> improve state example

- Cargo.toml
- self-shutdown-route/Cargo.toml
- self-shutdown-route/README.md
- self-shutdown-route/src/main.rs
in response to actix/actix-web#1315
> add self shutdown route example

- state/src/main.rs
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Also demonstrate how to pass shared counters via Atomic

- todo/src/main.rs
Hi,
This PR fixes the leading slash error pointed out in #247.
Closes #247.
> Fix templates path

- README.md
I've spent several months creating a full-featured implementation and recently converted it to Actix 2.0.  I think this could help answer a lot of questions on how to implement Actix in a production/enterprise setup.  The description in the README is long, but wanted to show "what you get".   Let me know if you want this edited.  Thanks for considering!
> Add Complete Actix 2.x REST Server to the community section of README

- Cargo.toml
- docker_sample/Cargo.toml
- docker_sample/Dockerfile
- docker_sample/README.MD
- docker_sample/src/main.rs
Build image:
```shell
docker build -t docker_sample --force-rm --no-cache -f  Dockerfile .
```
Run image:
```shell
echo "== start sample_docker"
docker run -d -p 5000:5000 docker_sample &
docker ps
echo "== wait 3s for startup"
sleep 3s
echo "== curl both routes"
curl http://localhost:5000
curl http://localhost:5000/again 
```
> Add `docker_sample` to examples collection

- Cargo.toml
- casbin/Cargo.toml
- casbin/README.md
- casbin/rbac/rbac_model.conf
- casbin/rbac/rbac_policy.csv
- casbin/src/main.rs
Casbin-RS is a powerful and efficient open-source access control library for Rust projects. It provides support for enforcing authorization based on various access control models.
Here is a basic example, hope to help those who want to use it.
> Add a basic casbin example for actix-web.

- multipart-s3/Cargo.toml
- multipart-s3/src/utils/s3.rs
Update `rusoto` dependencies to 0.43.0 and remove `RusotoFuture`, this should make CI happy.
> Update `rusoto` dependencies to 0.43.0

- jsonrpc/src/main.rs
> jsonrpc: Fix AppState extraction

- multipart-s3/Cargo.toml
- multipart-s3/src/main.rs
- multipart-s3/src/utils/s3.rs
- multipart-s3/src/utils/upload.rs
Clean-up s3 example to remove warnings roughly.
> Clean-up s3 example

- async_db/src/db.rs
- async_db/src/main.rs
- async_ex2/src/handlers/parts.rs
- async_ex2/src/handlers/products.rs
- async_pg/src/main.rs
- awc_https/src/main.rs
- docker_sample/src/main.rs
- graphql-demo/src/db.rs
- graphql-demo/src/schemas/product.rs
- graphql-demo/src/schemas/root.rs
- graphql-demo/src/schemas/user.rs
- jsonrpc/src/main.rs
- middleware/src/main.rs
- r2d2/src/main.rs
- server-sent-events/src/main.rs
- shutdown-server/src/main.rs
- state/src/main.rs
- todo/src/api.rs
- todo/src/model.rs
It makes CI logs more readable.
> Clean-up things

- graphql-demo/Cargo.toml
- hello-world/Cargo.toml
- http-proxy/Cargo.toml
- json/Cargo.toml
- jsonrpc/Cargo.toml
- middleware/Cargo.toml
- multipart/Cargo.toml
- openssl/Cargo.toml
- redis-session/Cargo.toml
- redis/Cargo.toml
- run-in-thread/Cargo.toml
- rustls/Cargo.toml
- server-sent-events/Cargo.toml
It almost updates `env_logger`.
> part2: Update dependencies

- websocket-chat/src/server.rs
Signed-off-by: Bart Willems <bwillems@protonmail.com>
> removed unwraps from websocket-chat

- .gitignore
- Cargo.toml
- websocket-chat-broker/Cargo.toml
- websocket-chat-broker/src/main.rs
- websocket-chat-broker/src/message.rs
- websocket-chat-broker/src/server.rs
- websocket-chat-broker/src/session.rs
- websocket-chat-broker/static/index.html
- upgrade dependencies
- re-structure & clean-up
- remove jquery from client side
- small style improvements client side
<details>
<summary>Style Improvements Preview</summary>
</details>
part clo_ses #292
> websocket chat broker improvements

- README.md
github.com/kriry no longer available
fixed #283
> update dead kriry source link

- Cargo.toml
- template_yarte/Cargo.toml
- template_yarte/build.rs
- template_yarte/src/main.rs
- template_yarte/templates/deep/more/card/form.hbs
- template_yarte/templates/deep/more/deep/welcome.hbs
- template_yarte/templates/deep/more/doc/head.hbs
Update yarte example with latest features.  
And fix `simple-auth-server` depend on `bindgen@0.48` incompatible with latest versions of `clang`
> Update yarte version to 0.8

- simple-auth-server/src/auth_handler.rs
This is arguably simpler, right?
> Refactor FromRequest for LoggedUser in simple-auth-server

- diesel/src/main.rs
> remove `diesel=debug` in env var

- docker_sample/Dockerfile
- docker_sample/README.MD
- docker_sample/src/main.rs
Prefetch dependencies in separate layers to optimize build.
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>
> update docker sample by caching dependencies

- form/static/form.html
> Fix typo in form example html

- multipart-async-std/src/main.rs
- multipart/src/main.rs
I noticed a minor inconsistency. The `<input type="submit"...>` was used as the start tag with `</button>` as the end tag.
I have chosen to use `<button>`, since it can contain html inside it. See [this StackOverflow](https://stackoverflow.com/a/7117673/78336) answer.
> Corrected mismatch between html start tag and html end tag.

- README.md
At first, I found it hard to handle images coming from POST requests (problems with base64, formats, etc.). Thus, I propose a repository of mine as an example from the community: https://github.com/carrascomj/dalted
It provides an example of integration with [image-rs](https://github.com/image-rs/image) for a web-app, with the following features:
* Simple workflow to [accept an image from a POST request](https://github.com/carrascomj/dalted/blob/master/src/routes/post.rs#L15), [transform](https://github.com/carrascomj/dalted/blob/master/src/image_processing/pipe_transform.rs#L32) the image and return the transformed results to the front-end (with a bit of [serde](https://serde.rs/) in the process).
* Minimal Front-end with HTML5 (it doesn't use any web-framework). It solely uses …
> add example from community about image processing

- todo/Cargo.toml
- todo/src/main.rs
- todo/templates/index.html.tera
examples/todo have issue of XSS.
> Escape HTML

- template_handlebars/src/main.rs
```
#[get("/{user}/{data}")]
/hi/baby
===========
info: web::Path<(String, String)>
info=>("hi", "baby")
info.0=>("hi", "baby")
info.0.0=>"hi"
info.0.1=>"baby"
info.1=>"baby"
====Fixed====
web::Path(info): web::Path<(String, String)>
info=>("hi", "baby")
info.0=>"hi"
info.1=>"baby"
```
> Fix Path derefs

- README.md
[**`binserve`**](https://github.com/mufeedvh/binserve) is a fast static web server with features like routing, templating, security, etc written on top of `actix-web`.
:arrow_right: [README.md](https://github.com/mufeedvh/binserve/blob/master/README.md)
> Added binserve to community examples

- websocket-chat/static/websocket.html
simplified js code as same functions without jQuery
> js without jQuery

- websocket-chat-broker/Cargo.toml
- websocket-chat-broker/src/main.rs
Upgrading example to actix v3 as dependent actix-broker now can handle the move.
> Upgrade websocket-chat-broker example to actix V3 and actix-broker 3.1

- README.md
Related [Reddit comment](https://www.reddit.com/r/rust/comments/jv6a5j/productiongrade_logging_in_rust_applications/gcib8ml?utm_source=share&utm_medium=web2x&context=3).
> Adds an article on the use of tracing in actix

- Cargo.lock
- template_yarte/Cargo.toml
- template_yarte/README.md
- template_yarte/src/main.rs
- template_yarte/templates/index.hbs
> Refactor template yarte example for use bytes implementation

- basics/README.md
- basics/static/404.html
- basics/static/welcome.html
- Fixed broken link in readme.
- Removed pixel unit from `<img>` tag. 
- Removed slashes in `<img>` tag and `<link>` tag.
> Improve the "basics" example

- Cargo.lock
- template_engines/yarte/Cargo.toml
- template_engines/yarte/src/main.rs
Add `auto!`, auto-sized buffer functionality.
> Update yarte to 0.15

- README.md
> Add zero2prod

- README.md
Please consider adding [mCaptcha](https://github.com/mCaptcha/mCaptcha) to community showcase
> add mCaptcha to community showcase

- security/rustls/README.md
The steps were muddled for me so here my attempt to improve.
> docs: improve rustls example

- README.md
Well, as in title, it adds Imitari project.
> Add Imitari project

- basics/http-proxy/src/main.rs
Do not store request and response body as whole in memory.
> enable two way streaming for proxy.

- json/json_error/Cargo.toml
Updated to v4. No further changes necessary.
> Updated json/json_error to v4.

- basics/static_index/Cargo.toml
Issues encountered: None :) only bumped Cargo.toml
> Update basics/static-index to v4.

- json/json_decode_error/Cargo.toml
Literally just changed the version, no other changes required.
> Updated json/json_decode_error to v4

- forms/multipart-s3/Cargo.toml
- forms/multipart-s3/src/utils/upload.rs
Fixed file i/o and moved from external `bytes` crate to `actix_web::web::Bytes`.
> Updated forms/multipart-s3 to v4.

- forms/multipart/Cargo.toml
- forms/multipart/README.md
- forms/multipart/src/main.rs
Mainly changed the handling of the file opening. Also updated the README to correctly describe the listening port.
> Updated forms/multipart to v4.

- security/rustls-client-cert/Cargo.toml
- security/rustls-client-cert/src/main.rs
Updated to v4. The parsing of the certificates and keys is quite verbose in the new version..
> Rustls client cert

- Cargo.lock
- basics/hello-world/Cargo.toml
- basics/hello-world/src/main.rs
Issues encountered along the way: `ServiceResponse::response().body() -> &BoxBody` was
replaced by `ServiceResponse::into_body()`.
> Update basics/hello-world to v4.

- database_interactions/rbatis/README.md
This pull request is a reaction to/replacement of the stagnating PR #381. 
I feel like this is simple and straightforward solution.
> [Feature] Add simple README linking to rbatis examples.

- Cargo.lock
- basics/docker_sample/Cargo.toml
- basics/docker_sample/README.MD
Removed deprecated test build target. Readme file updated to reflect the actual state of code. Corrected internal container's and host's exposed port numbers.
> Updated basics/docker_sample to v4.

- security/rustls/Cargo.toml
- security/rustls/src/main.rs
Simple update,  changed the parsing of keys/ certs and the configuration builder.
> Updated security/rustls to v4.

- basics/nested-routing/Cargo.toml
- basics/nested-routing/src/handlers/products.rs
Changed header attachment in test to use `insert_header`.
> Updated basics/nested-routing to v4.

- Cargo.lock
- security/web-cors/backend/Cargo.toml
- security/web-cors/frontend/package.json
- Upgrade `actix-web` to v4
- Pin `vue-template-compiler` version to fix `Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined` error.
> Upgrade security/web-cors to v4

- security/casbin/Cargo.toml
Another simple update, no changes to the code. Removed some unnecessary dependancies.
> Updated security/casbin to v4.

- security/openssl/Cargo.toml
- security/openssl/src/main.rs
Another simple update, the only change was `header` -> `append_header` in the constructor.
> Updated security/openssl to v4.

- .github/workflows/clippy-fmt.yml
- Cargo.lock
- Cargo.toml
- security/openssl-auto-le/Cargo.toml
- security/openssl-auto-le/README.md
- security/openssl-auto-le/src/main.rs
> Adding auto OpenSSL ACME Let's Encrypt example.

- other/server-sent-events/Cargo.toml
- other/server-sent-events/README.md
- other/server-sent-events/benchmark.js
- other/server-sent-events/drain.js
- other/server-sent-events/src/index.html
- other/server-sent-events/src/main.rs
I upgraded to v4. I had to add tokio-stream as a dependency as the stream based stuff used in the example did not make it into tokio v1. I also had to fiddle with the `.js` scripts, as using `localhost` in the http requests didn't work for some reason.
> Updated others/server-sent-events to v4.

- Cargo.lock
- database_interactions/redis/Cargo.toml
- database_interactions/redis/README.md
- database_interactions/redis/src/main.rs
I updated to V4. I'm not sure if the way I am converting errors from `actix::MailboxError` to `actix_web::Error` is idiomatic, but it works. Other than that everything was simple.
> Database interactions/redis

- README.md
> Add pict-rs to community examples

- auth/cookie-session/src/main.rs
To play nice with the web eco, please consider renaming the primary branch to `main`.  I updated the only usage of `master` in the code.
Please see https://github.com/github/renaming#renaming-the-default-branch-from-master
Thanks!
> Use branch agnostic link

- Cargo.lock
- auth/redis-session/Cargo.toml
- auth/redis-session/src/main.rs
close #544
- update example `redis-session`
- pass test
- remove `actix-redis`
Note:
I'm a beginner in Rust.
> update example redis-session

- websockets/echo/websocket-client.py
> Bug fix for websocket chat python file

- server-sent-events/README.md
Example didn't work, you need to send a Post request to send a message but curl defaults to Get
> fix SSE instructions

- README.md
hey @robjtede , I've added my personal project that download object from google cloud storage, but it's proxied from Actix Web protected with basic auth and BASE64 Service Account of Google Cloud Platform. Hopefully it can help to gain more engagement in this showcase / example !
Thanks !
> add gcs-proxy to the showcase readme

- forms/form/src/main.rs
```sh
cd forms/form
cargo test
```
> fix test for forms/form

- .github/workflows/clippy-fmt.yml
- .github/workflows/linux.yml
We can finally drop all the use of actions-rs by this.
> Refine GHA workflows

- databases/mysql/Cargo.toml
- databases/mysql/README.md
- databases/mysql/apis/addbank.txt
- databases/mysql/apis/addbranch.txt
- databases/mysql/apis/addcustomer.txt
- databases/mysql/apis/addteller.txt
- databases/mysql/apis/getbank.txt
- databases/mysql/apis/getbranch.txt
- databases/mysql/apis/getcustomer.txt
- databases/mysql/apis/getteller.txt
- databases/mysql/sql/bankdetails.sql
- databases/mysql/sql/branch_details.sql
- databases/mysql/sql/customer_details.sql
- databases/mysql/sql/teller_details.sql
- databases/mysql/src/db_layer.rs
- databases/mysql/src/main.rs
This RESTful Actix Web API example illustrates how to connect to MySQL database using Mysql client library implemented in rust i.e MySql database driver
>  Add example for Mysql client library (MySql database driver) #622

- README.md
Add a new community example for rayspace.dev: Minimalist dev portfolio and blog example featuring GitHub OAuth, session management, HTTP Server for SPA, API endpoints, and SQLx integration.
> Add community example: rayspace.dev

- README.md
Hello,
Hopefully I did this right, always a little worried.
I updated the README in the examples and added a link to the Actix-Web template I created to start an API project and host it on Shuttle.
> improvement: add readme item for shuttle-template-actix

- README.md
Proposition for a community example of a blog showcasing the use of actix with diesel and r2d2 and API endpoints. 
Usage with react.
> Add community example: a simple blog for markdown rendering 

- README.md
Hello there,
I am adding my submission, a boilerplate project that contains a JWT implementation on Actix, with Angular frontend and PostgreSQL that is already Dockerized.
Best regards!
> update(README.md): adds Angular + Actix with JWT security example

- README.md
Hey,
I am adding my submission, a boilerplate project that uses NextJs frontend, prisma for the database and user/identity system.
Best regards!
>  update(README.md): adds Planters Cycle example

- middleware/http-to-https/README.md
I'm not sure that I updated it to the correct example but it was my best guess
> fix: update broken link

- Cargo.lock
- background-jobs/Cargo.toml
- background-jobs/src/persistent_jobs.rs
- background-jobs/src/routes.rs
- Updates the code to the latest version of apalis pending v0.6 release
- Removes monitor as it didn't serve any purpose.
> Chore: Update apalis to the latest version

- Cargo.lock
- background-jobs/Cargo.toml
- background-jobs/src/persistent_jobs.rs
- Updates to the latest version of apalis
> chore: update the apalis example to the latest version

- websockets/chat-actorless/src/handler.rs
I noticed the TODO comment "nested select is pretty gross for readability on the match" in the example. To address this, I replaced the usage with tokio::select!, which simplifies the control flow and improves readability, especially around pattern matching.
According to [this thread](https://users.rust-lang.org/t/why-doesnt-tokio-select-require-fusedfuture/46975) on the Rust forums, tokio::select! is more ergonomic than futures::select!, as it does not require FusedFuture, pin!, or additional boilerplate.
> refactor: improve select usage with tokio::select! macro in websockets/actor-actorless example
